#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RetailMobile.Resource", IsApplication=true)]

namespace RetailMobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040006
			public const int action_bar1 = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int action_bar2 = 2130968583;
			
			// aapt resource value: 0x7f04000a
			public const int action_bar_text = 2130968586;
			
			// aapt resource value: 0x7f040000
			public const int background = 2130968576;
			
			// aapt resource value: 0x7f04000d
			public const int caption_text = 2130968589;
			
			// aapt resource value: 0x7f040003
			public const int dark_blue = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int disabled_background = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int foreground = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int light_blue = 2130968578;
			
			// aapt resource value: 0x7f04000b
			public const int main_background_1 = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int main_background_2 = 2130968588;
			
			// aapt resource value: 0x7f040008
			public const int menu_button1 = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int menu_button2 = 2130968585;
			
			// aapt resource value: 0x7f040004
			public const int yellow = 2130968580;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050004
			public const int action_bar_button_bottom_margin = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int action_bar_button_height = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int action_bar_button_left_margin = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int action_bar_button_right_margin = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int action_bar_button_top_margin = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int action_bar_button_width = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int action_bar_height = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int button_corners_radius = 2131034119;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int actionbar_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int add_48 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int back_48 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int barcode_32 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int border = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int button_background = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int button_background_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int button_selector = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int cash_register_icon64 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int checkbox_unchecked_16 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int close_icon32 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int close_icon64 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int coins_icon64 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int customers_64 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int customersIcon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int delete_icon16 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int delete_icon24 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int door = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int edit_icon16 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int edit_icon1_24 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int edit_icon32 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int filterTextEditBackground = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int filterTextEditBackgroundFocused = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int filterTextEditStyle = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int floppy_32 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int grass = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int gridTextEditBackground = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int gridTextEditBackgroundFocused = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int gridTextEditStyle = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int header = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int Icon = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int invoice_64 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int invoice_icon64 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int invoiceIcon = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int items_64 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int itemsIcon = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int kamenitza = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int line_chart_icon64 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int main_button_selector = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int main_icon = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int menu_button_background = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int menu_button_background_pressed = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int menu_button_selector = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int menu_caption_background = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int MenuButtonBackgroundNormal = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int MenuButtonBackgroundPressed = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int MenuButtonStyle = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int minus_64 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int my_edit_text_background_disabled = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int my_edit_text_background_focused = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int my_edit_text_background_normal = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int my_edit_text_selector1 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int my_edit_text_selector2 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int night = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int no_icon = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int no_image = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int parentBackground = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int parentBackground1 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int plus_64 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int reportsIcon = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int retail = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int save_48 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int search16 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int search_128 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int settings_48 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int shop_cart_add_icon32 = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int shop_cart_add_icon64 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int shopping_basket_add_32 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int shopping_cart_icon64 = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int sync_48 = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int table_cell_bg = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int table_header_cell_bg = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int textEditBackground = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int textEditBackgroundFocused = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int TextEditStyle = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int tick_16 = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int user_group_icon64 = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int window = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int zagorka = 2130837582;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0900a9
			public const int ActionBar = 2131296425;
			
			// aapt resource value: 0x7f0900ae
			public const int ActionBarList = 2131296430;
			
			// aapt resource value: 0x7f0900a7
			public const int ActionBarMain = 2131296423;
			
			// aapt resource value: 0x7f0900ac
			public const int LayoutMenu = 2131296428;
			
			// aapt resource value: 0x7f090089
			public const int LeftButtons = 2131296393;
			
			// aapt resource value: 0x7f09008a
			public const int RightButtons = 2131296394;
			
			// aapt resource value: 0x7f090036
			public const int btnAddCustomer = 2131296310;
			
			// aapt resource value: 0x7f090030
			public const int btnAddInvoice = 2131296304;
			
			// aapt resource value: 0x7f090033
			public const int btnAddItem = 2131296307;
			
			// aapt resource value: 0x7f090096
			public const int btnAddItems = 2131296406;
			
			// aapt resource value: 0x7f090067
			public const int btnAddValue = 2131296359;
			
			// aapt resource value: 0x7f090021
			public const int btnClose = 2131296289;
			
			// aapt resource value: 0x7f090097
			public const int btnCloseItemSearch = 2131296407;
			
			// aapt resource value: 0x7f0900a3
			public const int btnLogin = 2131296419;
			
			// aapt resource value: 0x7f0900bc
			public const int btnLogout = 2131296444;
			
			// aapt resource value: 0x7f0900b2
			public const int btnMainSync = 2131296434;
			
			// aapt resource value: 0x7f090022
			public const int btnOK = 2131296290;
			
			// aapt resource value: 0x7f090017
			public const int btnSave = 2131296279;
			
			// aapt resource value: 0x7f090062
			public const int btnScan = 2131296354;
			
			// aapt resource value: 0x7f090049
			public const int btnSearchCustomer = 2131296329;
			
			// aapt resource value: 0x7f090063
			public const int btnSearchItems = 2131296355;
			
			// aapt resource value: 0x7f0900a4
			public const int btnSettings = 2131296420;
			
			// aapt resource value: 0x7f090068
			public const int btnSubstractValue = 2131296360;
			
			// aapt resource value: 0x7f0900a5
			public const int btnSync = 2131296421;
			
			// aapt resource value: 0x7f09001c
			public const int captionCode = 2131296284;
			
			// aapt resource value: 0x7f09001f
			public const int captionDebt = 2131296287;
			
			// aapt resource value: 0x7f09001d
			public const int captionName = 2131296285;
			
			// aapt resource value: 0x7f09001e
			public const int captionTaxNum = 2131296286;
			
			// aapt resource value: 0x7f090029
			public const int cbCateg1 = 2131296297;
			
			// aapt resource value: 0x7f09002b
			public const int cbCateg2 = 2131296299;
			
			// aapt resource value: 0x7f090092
			public const int cbItemCateg1 = 2131296402;
			
			// aapt resource value: 0x7f090094
			public const int cbItemCateg2 = 2131296404;
			
			// aapt resource value: 0x7f090073
			public const int checkBox = 2131296371;
			
			// aapt resource value: 0x7f090005
			public const int date = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int date_icon = 2131296262;
			
			// aapt resource value: 0x7f0900ab
			public const int detailInfo_fragment = 2131296427;
			
			// aapt resource value: 0x7f0900aa
			public const int details_fragment = 2131296426;
			
			// aapt resource value: 0x7f090004
			public const int gridview = 2131296260;
			
			// aapt resource value: 0x7f090000
			public const int header = 2131296256;
			
			// aapt resource value: 0x7f090098
			public const int imgChecked = 2131296408;
			
			// aapt resource value: 0x7f090018
			public const int imgCustomer = 2131296280;
			
			// aapt resource value: 0x7f090035
			public const int imgCustomers = 2131296309;
			
			// aapt resource value: 0x7f090042
			public const int imgCustomersIcon = 2131296322;
			
			// aapt resource value: 0x7f09002f
			public const int imgInvoice = 2131296303;
			
			// aapt resource value: 0x7f09004b
			public const int imgInvoiceIcon = 2131296331;
			
			// aapt resource value: 0x7f09006c
			public const int imgItem = 2131296364;
			
			// aapt resource value: 0x7f090083
			public const int imgItemDetail = 2131296387;
			
			// aapt resource value: 0x7f09002d
			public const int imgItemSelected = 2131296301;
			
			// aapt resource value: 0x7f090032
			public const int imgItems = 2131296306;
			
			// aapt resource value: 0x7f09003e
			public const int invoice_items_alphabet = 2131296318;
			
			// aapt resource value: 0x7f09003f
			public const int invoice_items_list = 2131296319;
			
			// aapt resource value: 0x7f0900af
			public const int ivMenuIcon = 2131296431;
			
			// aapt resource value: 0x7f090087
			public const int layoutAct = 2131296391;
			
			// aapt resource value: 0x7f090086
			public const int layoutActionBar = 2131296390;
			
			// aapt resource value: 0x7f090095
			public const int layoutBottomButtons = 2131296405;
			
			// aapt resource value: 0x7f090061
			public const int layoutButtons = 2131296353;
			
			// aapt resource value: 0x7f090041
			public const int layoutCustomerInfo = 2131296321;
			
			// aapt resource value: 0x7f090059
			public const int layoutDetails = 2131296345;
			
			// aapt resource value: 0x7f09005b
			public const int layoutDetailsGridCaptions = 2131296347;
			
			// aapt resource value: 0x7f090040
			public const int layoutHeader = 2131296320;
			
			// aapt resource value: 0x7f09008b
			public const int layoutHeaderFilter = 2131296395;
			
			// aapt resource value: 0x7f0900b3
			public const int layoutIP = 2131296435;
			
			// aapt resource value: 0x7f090081
			public const int layoutImg = 2131296385;
			
			// aapt resource value: 0x7f09004a
			public const int layoutInvoiceInfo = 2131296330;
			
			// aapt resource value: 0x7f09009d
			public const int layoutItemCategs = 2131296413;
			
			// aapt resource value: 0x7f090099
			public const int layoutItemInfoCodeName = 2131296409;
			
			// aapt resource value: 0x7f0900a0
			public const int layoutItemPrices = 2131296416;
			
			// aapt resource value: 0x7f0900ad
			public const int layoutList = 2131296429;
			
			// aapt resource value: 0x7f0900b6
			public const int layoutPort = 2131296438;
			
			// aapt resource value: 0x7f0900b9
			public const int layoutSyncModel = 2131296441;
			
			// aapt resource value: 0x7f0900b1
			public const int layoutTop = 2131296433;
			
			// aapt resource value: 0x7f09006b
			public const int layout_checkable_item_info = 2131296363;
			
			// aapt resource value: 0x7f090088
			public const int lblCaption = 2131296392;
			
			// aapt resource value: 0x7f090013
			public const int lblCustAddress = 2131296275;
			
			// aapt resource value: 0x7f090044
			public const int lblCustCode = 2131296324;
			
			// aapt resource value: 0x7f090048
			public const int lblCustDebt = 2131296328;
			
			// aapt resource value: 0x7f090045
			public const int lblCustName = 2131296325;
			
			// aapt resource value: 0x7f090046
			public const int lblCustPhone = 2131296326;
			
			// aapt resource value: 0x7f090010
			public const int lblCustTaxNum = 2131296272;
			
			// aapt resource value: 0x7f090012
			public const int lblCustTaxNumError = 2131296274;
			
			// aapt resource value: 0x7f090043
			public const int lblCustomerCaption = 2131296323;
			
			// aapt resource value: 0x7f09000b
			public const int lblCustomerCode = 2131296267;
			
			// aapt resource value: 0x7f090009
			public const int lblCustomerInfoCaption = 2131296265;
			
			// aapt resource value: 0x7f09000e
			public const int lblCustomerName = 2131296270;
			
			// aapt resource value: 0x7f09005e
			public const int lblDetDisc = 2131296350;
			
			// aapt resource value: 0x7f090037
			public const int lblDetItemCode = 2131296311;
			
			// aapt resource value: 0x7f090038
			public const int lblDetItemDesc = 2131296312;
			
			// aapt resource value: 0x7f09005f
			public const int lblDetNetValue = 2131296351;
			
			// aapt resource value: 0x7f09005d
			public const int lblDetQty = 2131296349;
			
			// aapt resource value: 0x7f09005c
			public const int lblDetUnitPrice = 2131296348;
			
			// aapt resource value: 0x7f090060
			public const int lblDetVatValue = 2131296352;
			
			// aapt resource value: 0x7f09005a
			public const int lblDetailsCaption = 2131296346;
			
			// aapt resource value: 0x7f0900c5
			public const int lblDtrnQty = 2131296453;
			
			// aapt resource value: 0x7f0900be
			public const int lblDtrn_ItemCode = 2131296446;
			
			// aapt resource value: 0x7f0900c6
			public const int lblDtrn_disc_line1 = 2131296454;
			
			// aapt resource value: 0x7f0900c3
			public const int lblDtrn_net_value = 2131296451;
			
			// aapt resource value: 0x7f0900c2
			public const int lblDtrn_unit_price = 2131296450;
			
			// aapt resource value: 0x7f0900c4
			public const int lblDtrn_vat_value = 2131296452;
			
			// aapt resource value: 0x7f09008c
			public const int lblFilter = 2131296396;
			
			// aapt resource value: 0x7f09008d
			public const int lblFilterCode = 2131296397;
			
			// aapt resource value: 0x7f09008f
			public const int lblFilterDesc = 2131296399;
			
			// aapt resource value: 0x7f090074
			public const int lblHeaderImgItem = 2131296372;
			
			// aapt resource value: 0x7f090075
			public const int lblHeaderItemCode = 2131296373;
			
			// aapt resource value: 0x7f090079
			public const int lblHeaderItemLastBuyDate = 2131296377;
			
			// aapt resource value: 0x7f090076
			public const int lblHeaderItemName = 2131296374;
			
			// aapt resource value: 0x7f090078
			public const int lblHeaderItemQtyLeft = 2131296376;
			
			// aapt resource value: 0x7f090077
			public const int lblHeaderItemSaleVal = 2131296375;
			
			// aapt resource value: 0x7f09007a
			public const int lblHeaderQty = 2131296378;
			
			// aapt resource value: 0x7f09004f
			public const int lblHtrnDate = 2131296335;
			
			// aapt resource value: 0x7f090051
			public const int lblHtrnExpln = 2131296337;
			
			// aapt resource value: 0x7f09004d
			public const int lblHtrnID = 2131296333;
			
			// aapt resource value: 0x7f090053
			public const int lblHtrnNetValue = 2131296339;
			
			// aapt resource value: 0x7f090057
			public const int lblHtrnTotValue = 2131296343;
			
			// aapt resource value: 0x7f090055
			public const int lblHtrnVatValue = 2131296341;
			
			// aapt resource value: 0x7f0900b4
			public const int lblIP = 2131296436;
			
			// aapt resource value: 0x7f09004c
			public const int lblInvoiceInfoCaption = 2131296332;
			
			// aapt resource value: 0x7f090091
			public const int lblItemCat1ID = 2131296401;
			
			// aapt resource value: 0x7f090093
			public const int lblItemCat2ID = 2131296403;
			
			// aapt resource value: 0x7f090028
			public const int lblItemCategory1 = 2131296296;
			
			// aapt resource value: 0x7f09002a
			public const int lblItemCategory2 = 2131296298;
			
			// aapt resource value: 0x7f09007c
			public const int lblItemCode = 2131296380;
			
			// aapt resource value: 0x7f090082
			public const int lblItemImage = 2131296386;
			
			// aapt resource value: 0x7f09007b
			public const int lblItemInfoCaption = 2131296379;
			
			// aapt resource value: 0x7f090024
			public const int lblItemName = 2131296292;
			
			// aapt resource value: 0x7f090026
			public const int lblItemRetVal = 2131296294;
			
			// aapt resource value: 0x7f09007f
			public const int lblItemSaleVal = 2131296383;
			
			// aapt resource value: 0x7f09002c
			public const int lblItemSelectedInfo = 2131296300;
			
			// aapt resource value: 0x7f09007d
			public const int lblLongDesc = 2131296381;
			
			// aapt resource value: 0x7f0900b7
			public const int lblPort = 2131296439;
			
			// aapt resource value: 0x7f0900ba
			public const int lblSyncModel = 2131296442;
			
			// aapt resource value: 0x7f090007
			public const int linearLayout1 = 2131296263;
			
			// aapt resource value: 0x7f09000a
			public const int linearLayout2 = 2131296266;
			
			// aapt resource value: 0x7f090008
			public const int linearLayout4 = 2131296264;
			
			// aapt resource value: 0x7f09000d
			public const int linearLayout5 = 2131296269;
			
			// aapt resource value: 0x7f090016
			public const int llBottom = 2131296278;
			
			// aapt resource value: 0x7f090020
			public const int lvCustomers = 2131296288;
			
			// aapt resource value: 0x7f090064
			public const int lvDetails = 2131296356;
			
			// aapt resource value: 0x7f090023
			public const int lvItems = 2131296291;
			
			// aapt resource value: 0x7f090034
			public const int miCustomers = 2131296308;
			
			// aapt resource value: 0x7f0900cb
			public const int miDelete = 2131296459;
			
			// aapt resource value: 0x7f0900ca
			public const int miEdit = 2131296458;
			
			// aapt resource value: 0x7f09002e
			public const int miInvoices = 2131296302;
			
			// aapt resource value: 0x7f090031
			public const int miItems = 2131296305;
			
			// aapt resource value: 0x7f0900c9
			public const int miNew = 2131296457;
			
			// aapt resource value: 0x7f090003
			public const int next = 2131296259;
			
			// aapt resource value: 0x7f0900a6
			public const int pbSync1 = 2131296422;
			
			// aapt resource value: 0x7f090001
			public const int previous = 2131296257;
			
			// aapt resource value: 0x7f090015
			public const int svStatistic = 2131296277;
			
			// aapt resource value: 0x7f09006a
			public const int tabcontent_fragment = 2131296362;
			
			// aapt resource value: 0x7f090069
			public const int tabhost = 2131296361;
			
			// aapt resource value: 0x7f090014
			public const int tbCustAddress = 2131296276;
			
			// aapt resource value: 0x7f090019
			public const int tbCustCode = 2131296281;
			
			// aapt resource value: 0x7f090065
			public const int tbCustCode1 = 2131296357;
			
			// aapt resource value: 0x7f09001b
			public const int tbCustDebt = 2131296283;
			
			// aapt resource value: 0x7f09001a
			public const int tbCustName = 2131296282;
			
			// aapt resource value: 0x7f090066
			public const int tbCustName1 = 2131296358;
			
			// aapt resource value: 0x7f090047
			public const int tbCustPhone = 2131296327;
			
			// aapt resource value: 0x7f090011
			public const int tbCustTaxNum = 2131296273;
			
			// aapt resource value: 0x7f09000c
			public const int tbCustomerCode = 2131296268;
			
			// aapt resource value: 0x7f09000f
			public const int tbCustomerName = 2131296271;
			
			// aapt resource value: 0x7f09003b
			public const int tbDetDisc = 2131296315;
			
			// aapt resource value: 0x7f09003c
			public const int tbDetNetValue = 2131296316;
			
			// aapt resource value: 0x7f09003a
			public const int tbDetQty = 2131296314;
			
			// aapt resource value: 0x7f090039
			public const int tbDetUnitPrice = 2131296313;
			
			// aapt resource value: 0x7f0900c1
			public const int tbDtrn_disc_line1 = 2131296449;
			
			// aapt resource value: 0x7f0900c0
			public const int tbDtrn_qty1 = 2131296448;
			
			// aapt resource value: 0x7f09008e
			public const int tbFilterCode = 2131296398;
			
			// aapt resource value: 0x7f090090
			public const int tbFilterDesc = 2131296400;
			
			// aapt resource value: 0x7f090050
			public const int tbHtrnDate = 2131296336;
			
			// aapt resource value: 0x7f090052
			public const int tbHtrnExpln = 2131296338;
			
			// aapt resource value: 0x7f09004e
			public const int tbHtrnID = 2131296334;
			
			// aapt resource value: 0x7f0900c7
			public const int tbHtrnNetVal = 2131296455;
			
			// aapt resource value: 0x7f090054
			public const int tbHtrnNetValue = 2131296340;
			
			// aapt resource value: 0x7f090058
			public const int tbHtrnTotValue = 2131296344;
			
			// aapt resource value: 0x7f0900c8
			public const int tbHtrnVatVal = 2131296456;
			
			// aapt resource value: 0x7f090056
			public const int tbHtrnVatValue = 2131296342;
			
			// aapt resource value: 0x7f0900b5
			public const int tbIP = 2131296437;
			
			// aapt resource value: 0x7f09009e
			public const int tbItemCateg1 = 2131296414;
			
			// aapt resource value: 0x7f09009f
			public const int tbItemCateg2 = 2131296415;
			
			// aapt resource value: 0x7f09006d
			public const int tbItemCode = 2131296365;
			
			// aapt resource value: 0x7f090085
			public const int tbItemDebt = 2131296389;
			
			// aapt resource value: 0x7f0900bf
			public const int tbItemDesc = 2131296447;
			
			// aapt resource value: 0x7f090071
			public const int tbItemLastBuyDate = 2131296369;
			
			// aapt resource value: 0x7f09009c
			public const int tbItemLongDesc = 2131296412;
			
			// aapt resource value: 0x7f09006e
			public const int tbItemName = 2131296366;
			
			// aapt resource value: 0x7f090070
			public const int tbItemQtyLeft = 2131296368;
			
			// aapt resource value: 0x7f090080
			public const int tbItemRetVal = 2131296384;
			
			// aapt resource value: 0x7f09006f
			public const int tbItemSaleVal = 2131296367;
			
			// aapt resource value: 0x7f090084
			public const int tbItemTaxNum = 2131296388;
			
			// aapt resource value: 0x7f09007e
			public const int tbLongDesc = 2131296382;
			
			// aapt resource value: 0x7f0900a2
			public const int tbPassword = 2131296418;
			
			// aapt resource value: 0x7f0900b8
			public const int tbPort = 2131296440;
			
			// aapt resource value: 0x7f090072
			public const int tbQty = 2131296370;
			
			// aapt resource value: 0x7f090027
			public const int tbRetVal = 2131296295;
			
			// aapt resource value: 0x7f090025
			public const int tbSearch = 2131296293;
			
			// aapt resource value: 0x7f09009a
			public const int tbSearchItemCode = 2131296410;
			
			// aapt resource value: 0x7f09009b
			public const int tbSearchItemName = 2131296411;
			
			// aapt resource value: 0x7f0900bb
			public const int tbSyncModel = 2131296443;
			
			// aapt resource value: 0x7f0900a1
			public const int tbUsername = 2131296417;
			
			// aapt resource value: 0x7f0900bd
			public const int tbValue = 2131296445;
			
			// aapt resource value: 0x7f09003d
			public const int tblDetVatValue = 2131296317;
			
			// aapt resource value: 0x7f090002
			public const int title = 2131296258;
			
			// aapt resource value: 0x7f0900a8
			public const int titles_fragment = 2131296424;
			
			// aapt resource value: 0x7f0900b0
			public const int tvMenuCaption = 2131296432;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int calendar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int calendar_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CustomerDetails = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CustomerInfoRow = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int CustomersList = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int dialog_customer_search = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int dialog_item_search = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int FragmentMainMenu = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int InvoiceDetailRow = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int InvoiceItemsSelect = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int InvoiceScreen = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int InvoiceTabs = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int item_row_checkable = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int item_row_checkable_header = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int ItemDetails = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int ItemInfoRow = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int items_action_bar = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int ItemSearch = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int ItemSearchRow = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int ItemsList = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int LoginFragment = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int main_action_bar = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int MainMenu = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int MainMenuRow = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int MySpinner = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int SettingsFragment = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int SpinnerRow = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int TransDetRow = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int TransDetRow_header = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int TransHedRow = 2130903069;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int CustomerListContextMenu = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060051
			public const int ExitPrompt = 2131099729;
			
			// aapt resource value: 0x7f06004d
			public const int Logout = 2131099725;
			
			// aapt resource value: 0x7f060050
			public const int No = 2131099728;
			
			// aapt resource value: 0x7f06004b
			public const int Password = 2131099723;
			
			// aapt resource value: 0x7f060049
			public const int Settings = 2131099721;
			
			// aapt resource value: 0x7f060002
			public const int SpinnerAll = 2131099650;
			
			// aapt resource value: 0x7f06004a
			public const int Username = 2131099722;
			
			// aapt resource value: 0x7f06004f
			public const int Yes = 2131099727;
			
			// aapt resource value: 0x7f060040
			public const int alphabetEnglish = 2131099712;
			
			// aapt resource value: 0x7f060041
			public const int alphabetGreek = 2131099713;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f06003a
			public const int btnAddItems = 2131099706;
			
			// aapt resource value: 0x7f060042
			public const int btnAddNew = 2131099714;
			
			// aapt resource value: 0x7f060044
			public const int btnClose = 2131099716;
			
			// aapt resource value: 0x7f06003b
			public const int btnCloseItemSearch = 2131099707;
			
			// aapt resource value: 0x7f060043
			public const int btnList = 2131099715;
			
			// aapt resource value: 0x7f06004c
			public const int btnLogin = 2131099724;
			
			// aapt resource value: 0x7f060012
			public const int btnNew = 2131099666;
			
			// aapt resource value: 0x7f060045
			public const int btnOK = 2131099717;
			
			// aapt resource value: 0x7f06002f
			public const int btnSave = 2131099695;
			
			// aapt resource value: 0x7f06002e
			public const int btnScan = 2131099694;
			
			// aapt resource value: 0x7f060030
			public const int btnSearch = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int btnSearchCustomer = 2131099697;
			
			// aapt resource value: 0x7f06004e
			public const int btnSync = 2131099726;
			
			// aapt resource value: 0x7f06003c
			public const int cbItemCategPrompt = 2131099708;
			
			// aapt resource value: 0x7f060001
			public const int empty = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int lblCustDebt = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int lblCustTaxNum = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int lblCustomerAddress = 2131099653;
			
			// aapt resource value: 0x7f060032
			public const int lblCustomerCaption = 2131099698;
			
			// aapt resource value: 0x7f060003
			public const int lblCustomerCode = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int lblCustomerName = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int lblCustomerPhone = 2131099654;
			
			// aapt resource value: 0x7f060024
			public const int lblDetailsCaption = 2131099684;
			
			// aapt resource value: 0x7f060017
			public const int lblDtrnQty = 2131099671;
			
			// aapt resource value: 0x7f060019
			public const int lblDtrn_disc_line1 = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int lblDtrn_net_value = 2131099674;
			
			// aapt resource value: 0x7f060018
			public const int lblDtrn_unit_price = 2131099672;
			
			// aapt resource value: 0x7f06001b
			public const int lblDtrn_vat_value = 2131099675;
			
			// aapt resource value: 0x7f060007
			public const int lblEmptyList = 2131099655;
			
			// aapt resource value: 0x7f060027
			public const int lblHeaderItemCode = 2131099687;
			
			// aapt resource value: 0x7f06002c
			public const int lblHeaderItemLastBuyDate = 2131099692;
			
			// aapt resource value: 0x7f060028
			public const int lblHeaderItemName = 2131099688;
			
			// aapt resource value: 0x7f06002b
			public const int lblHeaderItemQtyLeft = 2131099691;
			
			// aapt resource value: 0x7f06002a
			public const int lblHeaderItemRetVal = 2131099690;
			
			// aapt resource value: 0x7f060029
			public const int lblHeaderItemSaleVal = 2131099689;
			
			// aapt resource value: 0x7f06002d
			public const int lblHeaderQty = 2131099693;
			
			// aapt resource value: 0x7f060035
			public const int lblHtrnDate = 2131099701;
			
			// aapt resource value: 0x7f060036
			public const int lblHtrnExpl = 2131099702;
			
			// aapt resource value: 0x7f060034
			public const int lblHtrnID = 2131099700;
			
			// aapt resource value: 0x7f060037
			public const int lblHtrnNetValue = 2131099703;
			
			// aapt resource value: 0x7f060039
			public const int lblHtrnTotValue = 2131099705;
			
			// aapt resource value: 0x7f060038
			public const int lblHtrnVatValue = 2131099704;
			
			// aapt resource value: 0x7f060046
			public const int lblIP = 2131099718;
			
			// aapt resource value: 0x7f060013
			public const int lblInvoice = 2131099667;
			
			// aapt resource value: 0x7f060033
			public const int lblInvoiceInfoCaption = 2131099699;
			
			// aapt resource value: 0x7f06001e
			public const int lblItemCategory1 = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int lblItemCategory2 = 2131099679;
			
			// aapt resource value: 0x7f06001c
			public const int lblItemCode = 2131099676;
			
			// aapt resource value: 0x7f060026
			public const int lblItemImage = 2131099686;
			
			// aapt resource value: 0x7f060025
			public const int lblItemInfoCaption = 2131099685;
			
			// aapt resource value: 0x7f06001d
			public const int lblItemName = 2131099677;
			
			// aapt resource value: 0x7f060022
			public const int lblItemQtyLeft = 2131099682;
			
			// aapt resource value: 0x7f060021
			public const int lblItemRetVal = 2131099681;
			
			// aapt resource value: 0x7f060023
			public const int lblItemSaleVal = 2131099683;
			
			// aapt resource value: 0x7f060020
			public const int lblLongDesc = 2131099680;
			
			// aapt resource value: 0x7f060047
			public const int lblPort = 2131099719;
			
			// aapt resource value: 0x7f060048
			public const int lblSyncModel = 2131099720;
			
			// aapt resource value: 0x7f06000e
			public const int miAddCustomer = 2131099662;
			
			// aapt resource value: 0x7f06000a
			public const int miCustomers = 2131099658;
			
			// aapt resource value: 0x7f060010
			public const int miDelete = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int miEdit = 2131099663;
			
			// aapt resource value: 0x7f06000c
			public const int miInvoice = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int miItems = 2131099659;
			
			// aapt resource value: 0x7f060011
			public const int miNew = 2131099665;
			
			// aapt resource value: 0x7f06000d
			public const int miReports = 2131099661;
			
			// aapt resource value: 0x7f060015
			public const int tvHeaderAmountCurr = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int tvHeaderAmountPrev = 2131099670;
			
			// aapt resource value: 0x7f060014
			public const int tvHeaderItemKategory = 2131099668;
			
			// aapt resource value: 0x7f06003e
			public const int tvMenuCaptionCustomers = 2131099710;
			
			// aapt resource value: 0x7f06003f
			public const int tvMenuCaptionInvoices = 2131099711;
			
			// aapt resource value: 0x7f06003d
			public const int tvMenuCaptionItems = 2131099709;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070010
			public const int ActionBarButton = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int ActionBarButtonLeft = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int ActionBarButtonRight = 2131165202;
			
			// aapt resource value: 0x7f070000
			public const int AppTheme = 2131165184;
			
			// aapt resource value: 0x7f070013
			public const int MyWindowTitle = 2131165203;
			
			// aapt resource value: 0x7f070015
			public const int cust_dialog = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int cust_dialogWrap = 2131165206;
			
			// aapt resource value: 0x7f070014
			public const int dialog_title_style = 2131165204;
			
			// aapt resource value: 0x7f07000d
			public const int fillHeight = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int fillParent = 2131165198;
			
			// aapt resource value: 0x7f07000c
			public const int fillWidth = 2131165196;
			
			// aapt resource value: 0x7f070009
			public const int headerText = 2131165193;
			
			// aapt resource value: 0x7f070006
			public const int listRowHeaderStyle = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int listRowTextViewHeaderStyle = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int listRowTextViewStyle = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int listStyle = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int mainButtonStyle = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int menuButtonStyle = 2131165191;
			
			// aapt resource value: 0x7f07000b
			public const int menu_background = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int menu_caption = 2131165194;
			
			// aapt resource value: 0x7f070001
			public const int myEditTextStyle = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int mySpinnerStyle = 2131165186;
			
			// aapt resource value: 0x7f07000f
			public const int wrapSelf = 2131165199;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
